//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int IdPerson { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int IdDocumentType { get; set; }
        public int DocumentNumber { get; set; }
        public string EMail { get; set; }
        public string PhoneNumbers { get; set; }
        public string Sex { get; set; }
        public System.DateTime Birthdate { get; set; }
        public Nullable<int> IdMaritalStatus { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Comments { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual MaritalStatus MaritalStatus { get; set; }
    }
}
