//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Example01Entities : DbContext
    {
        public Example01Entities()
            : base("name=Example01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<MaritalStatus> MaritalStatus { get; set; }
        public virtual DbSet<Person> Person { get; set; }
    
        public virtual ObjectResult<spGetPersonFilteredbyName_Result> spGetPersonFilteredbyName(string pSearchedName)
        {
            var pSearchedNameParameter = pSearchedName != null ?
                new ObjectParameter("pSearchedName", pSearchedName) :
                new ObjectParameter("pSearchedName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPersonFilteredbyName_Result>("spGetPersonFilteredbyName", pSearchedNameParameter);
        }
    }
}
